"""add knowledge base tables

Revision ID: 37d2b8fcfc4d
Revises: 540b945753b3
Create Date: 2025-11-21 14:45:04.248467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37d2b8fcfc4d'
down_revision: Union[str, Sequence[str], None] = '540b945753b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_bases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chatbot_id', sa.UUID(), nullable=False),
    sa.Column('collection_name', sa.String(length=255), nullable=False),
    sa.Column('vector_dimension', sa.Integer(), nullable=False),
    sa.Column('total_documents', sa.Integer(), nullable=False),
    sa.Column('total_chunks', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('total_chunks >= 0', name='valid_chunks_count'),
    sa.CheckConstraint('total_documents >= 0', name='valid_documents_count'),
    sa.CheckConstraint('vector_dimension > 0', name='valid_vector_dimension'),
    sa.ForeignKeyConstraint(['chatbot_id'], ['chatbots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_kb_chatbot_id', 'knowledge_bases', ['chatbot_id'], unique=False)
    op.create_index('idx_kb_collection_name', 'knowledge_bases', ['collection_name'], unique=False)
    op.create_index(op.f('ix_knowledge_bases_chatbot_id'), 'knowledge_bases', ['chatbot_id'], unique=True)
    op.create_index(op.f('ix_knowledge_bases_collection_name'), 'knowledge_bases', ['collection_name'], unique=True)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('knowledge_base_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('chunks_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'processing', 'completed', 'failed', 'skipped')", name='valid_document_status'),
    sa.CheckConstraint('(started_at IS NULL AND completed_at IS NULL) OR (started_at IS NOT NULL AND completed_at IS NULL) OR (started_at IS NOT NULL AND completed_at IS NOT NULL AND completed_at >= started_at)', name='valid_document_timing'),
    sa.CheckConstraint('chunks_count >= 0', name='valid_document_chunks_count'),
    sa.CheckConstraint('file_size >= 0', name='valid_document_file_size'),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_documents_checksum', 'documents', ['checksum'], unique=False)
    op.create_index('idx_documents_kb_id', 'documents', ['knowledge_base_id'], unique=False)
    op.create_index('idx_documents_kb_path', 'documents', ['knowledge_base_id', 'file_path'], unique=True)
    op.create_index('idx_documents_kb_status', 'documents', ['knowledge_base_id', 'status'], unique=False)
    op.create_index('idx_documents_status', 'documents', ['status'], unique=False)
    op.create_index(op.f('ix_documents_checksum'), 'documents', ['checksum'], unique=False)
    op.create_index(op.f('ix_documents_knowledge_base_id'), 'documents', ['knowledge_base_id'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('chunk_size', sa.Integer(), nullable=False),
    sa.Column('vector_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('chunk_index >= 0', name='valid_chunk_index'),
    sa.CheckConstraint('chunk_size > 0', name='valid_chunk_size'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chunks_document_chunk', 'document_chunks', ['document_id', 'chunk_index'], unique=True)
    op.create_index('idx_chunks_document_id', 'document_chunks', ['document_id'], unique=False)
    op.create_index('idx_chunks_vector_id', 'document_chunks', ['vector_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_vector_id'), 'document_chunks', ['vector_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_chunks_vector_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_index('idx_chunks_vector_id', table_name='document_chunks')
    op.drop_index('idx_chunks_document_id', table_name='document_chunks')
    op.drop_index('idx_chunks_document_chunk', table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_knowledge_base_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_checksum'), table_name='documents')
    op.drop_index('idx_documents_status', table_name='documents')
    op.drop_index('idx_documents_kb_status', table_name='documents')
    op.drop_index('idx_documents_kb_path', table_name='documents')
    op.drop_index('idx_documents_kb_id', table_name='documents')
    op.drop_index('idx_documents_checksum', table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_knowledge_bases_collection_name'), table_name='knowledge_bases')
    op.drop_index(op.f('ix_knowledge_bases_chatbot_id'), table_name='knowledge_bases')
    op.drop_index('idx_kb_collection_name', table_name='knowledge_bases')
    op.drop_index('idx_kb_chatbot_id', table_name='knowledge_bases')
    op.drop_table('knowledge_bases')
    # ### end Alembic commands ###
