"""create chatbot table

Revision ID: 540b945753b3
Revises: ed3874621c7f
Create Date: 2025-11-21 01:17:47.290326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '540b945753b3'
down_revision: Union[str, Sequence[str], None] = 'ed3874621c7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatbots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('llm_config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chatbots_name', 'chatbots', ['name'], unique=False)
    op.create_index(op.f('ix_chatbots_name'), 'chatbots', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chatbots_name'), table_name='chatbots')
    op.drop_index('idx_chatbots_name', table_name='chatbots')
    op.drop_table('chatbots')
    # ### end Alembic commands ###
