"""remove document chunks table

Revision ID: 6f5d0eab6447
Revises: c91f46a60438
Create Date: 2025-11-25 17:33:30.318173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f5d0eab6447'
down_revision: Union[str, Sequence[str], None] = 'c91f46a60438'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_chunks_document_chunk'), table_name='document_chunks')
    op.drop_index(op.f('idx_chunks_document_id'), table_name='document_chunks')
    op.drop_index(op.f('idx_chunks_vector_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_vector_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('chunk_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('chunk_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vector_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('document_chunks_document_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('document_chunks_pkey'))
    )
    op.create_index(op.f('ix_document_chunks_vector_id'), 'document_chunks', ['vector_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index(op.f('idx_chunks_vector_id'), 'document_chunks', ['vector_id'], unique=False)
    op.create_index(op.f('idx_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index(op.f('idx_chunks_document_chunk'), 'document_chunks', ['document_id', 'chunk_index'], unique=True)
    # ### end Alembic commands ###
