"""init database

Revision ID: ed3874621c7f
Revises: 
Create Date: 2025-11-21 00:19:38.245930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed3874621c7f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingest_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('process_id', sa.String(length=255), nullable=False),
    sa.Column('ingestion_type', sa.String(length=50), nullable=False),
    sa.Column('source_identifier', sa.String(length=500), nullable=False),
    sa.Column('source_metadata', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sub_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('total_files', sa.Integer(), nullable=False),
    sa.Column('files_processed', sa.Integer(), nullable=False),
    sa.Column('files_succeeded', sa.Integer(), nullable=False),
    sa.Column('files_failed', sa.Integer(), nullable=False),
    sa.Column('files_skipped', sa.Integer(), nullable=False),
    sa.Column('chunks_created', sa.Integer(), nullable=False),
    sa.Column('documents_added', sa.Integer(), nullable=False),
    sa.Column('error_messages', sa.JSON(), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('ingestion_config', sa.JSON(), nullable=True),
    sa.Column('processing_settings', sa.JSON(), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('client_info', sa.JSON(), nullable=True),
    sa.Column('environment_info', sa.JSON(), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'in_progress', 'completed', 'failed', 'cancelled')", name='valid_status'),
    sa.CheckConstraint('(started_at IS NULL AND completed_at IS NULL) OR (started_at IS NOT NULL AND completed_at IS NULL) OR (started_at IS NOT NULL AND completed_at IS NOT NULL AND completed_at >= started_at)', name='valid_timing'),
    sa.CheckConstraint('retry_count >= 0 AND retry_count <= max_retries', name='valid_retry_count'),
    sa.CheckConstraint('total_files >= 0 AND files_processed >= 0 AND files_succeeded >= 0 AND files_failed >= 0 AND files_skipped >= 0 AND files_processed = files_succeeded + files_failed + files_skipped', name='valid_file_counts'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ingest_jobs_active', 'ingest_jobs', ['status'], unique=False, postgresql_where="status IN ('pending', 'in_progress')")
    op.create_index('idx_ingest_jobs_completed_range', 'ingest_jobs', ['completed_at'], unique=False, postgresql_where='completed_at IS NOT NULL')
    op.create_index('idx_ingest_jobs_recent', 'ingest_jobs', ['created_at'], unique=False)
    op.create_index('idx_ingest_jobs_source_status', 'ingest_jobs', ['source_identifier', 'status'], unique=False)
    op.create_index('idx_ingest_jobs_status_created', 'ingest_jobs', ['status', 'created_at'], unique=False)
    op.create_index('idx_ingest_jobs_type_status', 'ingest_jobs', ['ingestion_type', 'status'], unique=False)
    op.create_index(op.f('ix_ingest_jobs_created_at'), 'ingest_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_ingest_jobs_ingestion_type'), 'ingest_jobs', ['ingestion_type'], unique=False)
    op.create_index(op.f('ix_ingest_jobs_process_id'), 'ingest_jobs', ['process_id'], unique=True)
    op.create_index(op.f('ix_ingest_jobs_source_identifier'), 'ingest_jobs', ['source_identifier'], unique=False)
    op.create_index(op.f('ix_ingest_jobs_status'), 'ingest_jobs', ['status'], unique=False)
    op.create_table('ingest_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('source_path', sa.String(length=1000), nullable=True),
    sa.Column('file_status', sa.String(length=20), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('file_type', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('chunks_created', sa.Integer(), nullable=False),
    sa.Column('documents_added', sa.Integer(), nullable=False),
    sa.Column('file_metadata', sa.JSON(), nullable=True),
    sa.CheckConstraint("file_status IN ('pending', 'processing', 'completed', 'failed', 'retry', 'skipped')", name='valid_file_status'),
    sa.CheckConstraint('(started_at IS NULL AND completed_at IS NULL) OR (started_at IS NOT NULL AND completed_at IS NULL) OR (started_at IS NOT NULL AND completed_at IS NOT NULL AND completed_at >= started_at)', name='valid_file_timing'),
    sa.CheckConstraint('chunks_created >= 0 AND documents_added >= 0', name='valid_processing_results'),
    sa.CheckConstraint('file_size IS NULL OR file_size >= 0', name='valid_file_size'),
    sa.ForeignKeyConstraint(['job_id'], ['ingest_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ingest_files_checksum', 'ingest_files', ['checksum'], unique=False)
    op.create_index('idx_ingest_files_completed_range', 'ingest_files', ['completed_at'], unique=False, postgresql_where='completed_at IS NOT NULL')
    op.create_index('idx_ingest_files_job_status', 'ingest_files', ['job_id', 'file_status'], unique=False)
    op.create_index('idx_ingest_files_path', 'ingest_files', ['file_path'], unique=False)
    op.create_index('idx_ingest_files_status_started', 'ingest_files', ['file_status', 'started_at'], unique=False)
    op.create_index(op.f('ix_ingest_files_checksum'), 'ingest_files', ['checksum'], unique=False)
    op.create_index(op.f('ix_ingest_files_file_path'), 'ingest_files', ['file_path'], unique=False)
    op.create_index(op.f('ix_ingest_files_file_status'), 'ingest_files', ['file_status'], unique=False)
    op.create_index(op.f('ix_ingest_files_job_id'), 'ingest_files', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingest_files_job_id'), table_name='ingest_files')
    op.drop_index(op.f('ix_ingest_files_file_status'), table_name='ingest_files')
    op.drop_index(op.f('ix_ingest_files_file_path'), table_name='ingest_files')
    op.drop_index(op.f('ix_ingest_files_checksum'), table_name='ingest_files')
    op.drop_index('idx_ingest_files_status_started', table_name='ingest_files')
    op.drop_index('idx_ingest_files_path', table_name='ingest_files')
    op.drop_index('idx_ingest_files_job_status', table_name='ingest_files')
    op.drop_index('idx_ingest_files_completed_range', table_name='ingest_files', postgresql_where='completed_at IS NOT NULL')
    op.drop_index('idx_ingest_files_checksum', table_name='ingest_files')
    op.drop_table('ingest_files')
    op.drop_index(op.f('ix_ingest_jobs_status'), table_name='ingest_jobs')
    op.drop_index(op.f('ix_ingest_jobs_source_identifier'), table_name='ingest_jobs')
    op.drop_index(op.f('ix_ingest_jobs_process_id'), table_name='ingest_jobs')
    op.drop_index(op.f('ix_ingest_jobs_ingestion_type'), table_name='ingest_jobs')
    op.drop_index(op.f('ix_ingest_jobs_created_at'), table_name='ingest_jobs')
    op.drop_index('idx_ingest_jobs_type_status', table_name='ingest_jobs')
    op.drop_index('idx_ingest_jobs_status_created', table_name='ingest_jobs')
    op.drop_index('idx_ingest_jobs_source_status', table_name='ingest_jobs')
    op.drop_index('idx_ingest_jobs_recent', table_name='ingest_jobs')
    op.drop_index('idx_ingest_jobs_completed_range', table_name='ingest_jobs', postgresql_where='completed_at IS NOT NULL')
    op.drop_index('idx_ingest_jobs_active', table_name='ingest_jobs', postgresql_where="status IN ('pending', 'in_progress')")
    op.drop_table('ingest_jobs')
    # ### end Alembic commands ###
